---
- name: Configure motd and banner
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

#collects device facts from the remote device running IOS.    
    - name: GET DEVICE FACTS
      ios_facts:

# ios_banner module used to define banners and messages of the day on Cisco IOS devices
# Banner choices: login / motd / exec / incomin / sip-ppp
# text can be defined here or as a variable called from another place.
    - name: CONFIGURE LOGIN BANNER
      ios_banner:
        banner: login
        text: | 
          Warning: Authorized employees only. 
          All others will be in trouble.
        state: present

# iosxr_banner module used for IOSXR Cisco Devices
# Banner choices: login / motd
    - name: configure the login banner
      iosxr_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present

# nxos_banner module for Cisco NXOS devices
# Banner choices: exce / motd
    - name: configure the exec banner
      nxos_banner:
        banner: exec
        text: |
          this is my exec banner
          that contains a multiline
          string
        state: present